class AppStrings {
  AppStrings._();

  static const String phoneForVerification = 'رقم الجوال لاستقبال رمز التحقق';
  static const String sendCode = 'ارسل الرمز';
  static const String error = 'خطأ';
  static const String attention = 'تنبيه';
  static const String ok = 'حسناً';
  static const String loginSuccess = 'تم تسجيل الدخول بنجاح';
  static const String login = 'تسجيل دخول';
  static const String createAccount = 'انشاء حساب';
  static const String phoneFieldLabel = 'رقم الجوال';
  static const String passwordFieldLabel = 'كلمة المرور';
  static const String writePhone = 'إكتب رقم الجوال';
  static const String writePassword = 'إكتب كلمة المرور';
  static const String forgotPassword = 'نسيت كلمة المرور ؟';
  static const String aboutSaaei = 'عن ساعي';
  static const String contactUs = 'اتصل بنا';
  static const String brokerLogin = 'الدخول كوسيط';
  static const String brokerRegister = 'التسجيل كوسيط';
  static const String nameFieldLabel = 'الإسم';
  static const String writeName = 'إكتب الإسم';
  static const String termsAndConditions = 'للشروط والأحكام';
  static const String registerSuccess = 'تم إنشاء الحساب بنجاح';
  static const String register = 'أنشئ حساب';
  static const String enterVerificationCode = 'ادخل رمز التحقق';
  static const String verify = 'تحقق';
  static const String otpIncomplete = 'يرجى إدخال رمز التحقق كاملاً';
  static const String acceptTermsRequired = 'يجب الموافقة على الشروط والأحكام للمتابعة';
  static const String enterNewPassword = 'ادخل كلمة المرور الجديدة';
  static const String writeNewPassword = 'إكتب كلمة المرور الجديدة';
  static const String reEnterNewPassword = 'أعد كتابة كلمة المرور الجديدة';
  static const String saveNewPassword = 'حفظ كلمة المرور الجديدة';
  static const String newPasswordFieldLabel = 'كلمة المرور الجديدة';
  static const String confirmPasswordFieldLabel = 'تأكيد كلمة المرور';
  static const String passwordsNotMatch = 'كلمات المرور غير متطابقتين';
  static const String confirm = 'تأكيد';
  static const String sendCodeError = 'فشل إرسال الرمز، يرجى التحقق من رقم الجوال';
  static const String sendLoginError = 'فشل تسجيل الدخول، يرجى التحقق من البيانات';
  static const String sendSignUpError = 'فشل إنشاء الحساب، يرجى المحاولة مرة أخرى';
  static const String sendResetPasswordError = 'فشل تغيير كلمة المرور، يرجى المحاولة مرة أخرى';
  static const String changePasswordSuccesfully = 'تم تغيير كلمة المرور بنجاح';
}
